import type { ArtifactItem, Connector, TaskItem, UploadedFile, UserProfile } from '@da-agent/shared';

export const currentUser: UserProfile = {
  email: 'phuthanh1206@gmail.com',
  name: 'Phu Thanh',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
  tokens: 50,
  plan: 'free',
};

export const initialTasks: TaskItem[] = [
  {
    id: 'task-1',
    title: 'Customer cohort retention analysis Q3',
    updatedAt: '2 hours ago',
    messageCount: 8,
    tags: ['Data', 'Python', 'Retention'],
    preview: 'Calculated 30-day and 90-day churn probabilities across enterprise segments.',
  },
  {
    id: 'task-2',
    title: 'Revenue forecast and seasonality model',
    updatedAt: 'Yesterday',
    messageCount: 14,
    tags: ['Forecasting', 'ARIMA', 'Finance'],
    preview: 'Generated Prophet trend projection with 95% confidence intervals.',
  },
  {
    id: 'task-3',
    title: 'Executive presentation slides on CAC vs LTV',
    updatedAt: '3 days ago',
    messageCount: 5,
    tags: ['Slides', 'Executive', 'Marketing'],
    preview: 'Exported 6 high-resolution executive slide decks with key payback metrics.',
  },
  {
    id: 'task-4',
    title: 'Web scraping and competitor pricing matrix',
    updatedAt: 'Last week',
    messageCount: 11,
    tags: ['Browser Agent', 'Scraping'],
    preview: 'Benchmarked 24 tier-1 SaaS competitors with automated price tracking.',
  },
];

export const initialFiles: UploadedFile[] = [
  {
    id: 'f-1',
    name: 'ecommerce_orders_2024.csv',
    size: 2458900,
    sizeFormatted: '2.4 MB',
    uploadDate: 'Sep 10, 2026, 14:32',
    type: 'csv',
    status: 'ready',
    dataRowCount: 48200,
    contentSnippet: 'order_id,customer_id,product_category,revenue,status,created_at',
  },
  {
    id: 'f-2',
    name: 'q3_financial_model_v4.xlsx',
    size: 1845100,
    sizeFormatted: '1.8 MB',
    uploadDate: 'Sep 09, 2026, 11:15',
    type: 'xlsx',
    status: 'ready',
    dataRowCount: 12500,
    contentSnippet: 'Department,Monthly_Budget,Actual_Spend,Variance_PCT',
  },
  {
    id: 'f-3',
    name: 'ad_campaign_metrics_meta_google.csv',
    size: 789400,
    sizeFormatted: '789 KB',
    uploadDate: 'Sep 08, 2026, 09:40',
    type: 'csv',
    status: 'ready',
    dataRowCount: 9400,
    contentSnippet: 'campaign_name,impressions,clicks,cpc,roas,conversions',
  },
];

export const initialArtifacts: ArtifactItem[] = [
  {
    id: 'art-1',
    title: 'Quarterly Revenue Cohort Heatmap',
    type: 'chart',
    createdAt: 'Sep 10, 2026',
    sourceTaskTitle: 'Customer cohort retention analysis Q3',
    dataSummary: 'Cohort retention from Jan 2024 to Aug 2024 showing 68% month-3 stickiness.',
  },
  {
    id: 'art-2',
    title: 'Executive Pitch Deck: Growth Drivers',
    type: 'slide',
    createdAt: 'Sep 09, 2026',
    sourceTaskTitle: 'Executive presentation slides on CAC vs LTV',
    dataSummary: 'Key slides reviewing unit economics, customer acquisition payback, and expansion revenue.',
  },
  {
    id: 'art-3',
    title: 'Cleaned Transaction Matrix Cleaned_v2.parquet',
    type: 'dataset',
    createdAt: 'Sep 08, 2026',
    sourceTaskTitle: 'Revenue forecast and seasonality model',
    dataSummary: 'Deduplicated dataset containing 128,400 normalized transactions with imputed missing values.',
  },
];

export const connectorsList: Connector[] = [
  {
    id: 'postgres',
    name: 'Postgres',
    description: 'Connect your Postgres data for instant AI analysis',
    category: 'databases',
    categoryLabel: 'Database',
    iconType: 'postgres',
    connected: false,
  },
  {
    id: 'bigquery',
    name: 'BigQuery',
    description: 'Connect your BigQuery data for instant AI analysis',
    category: 'data-warehouses',
    categoryLabel: 'Data Warehouse',
    iconType: 'bigquery',
    connected: false,
  },
  {
    id: 'snowflake',
    name: 'Snowflake',
    description: 'Connect your Snowflake data for instant AI analysis',
    category: 'data-warehouses',
    categoryLabel: 'Data Warehouse',
    iconType: 'snowflake',
    connected: false,
  },
  {
    id: 'mysql',
    name: 'MySQL',
    description: 'Connect your MySQL data for instant AI analysis',
    category: 'databases',
    categoryLabel: 'Database',
    iconType: 'mysql',
    connected: false,
  },
  {
    id: 'sqlserver',
    name: 'SqlServer',
    description: 'Connect your SqlServer data for instant AI analysis',
    category: 'databases',
    categoryLabel: 'Database',
    iconType: 'sqlserver',
    connected: false,
  },
  {
    id: 'supabase',
    name: 'Supabase',
    description: 'Connect your Supabase data for instant AI analysis',
    category: 'databases',
    categoryLabel: 'Database',
    iconType: 'supabase',
    connected: false,
  },
  {
    id: 'gdrive',
    name: 'Google Drive',
    description: 'Analyze your Google Drive files and folders',
    category: 'integrations',
    categoryLabel: 'Integration',
    iconType: 'gdrive',
    connected: true,
  },
  {
    id: 'gsheets',
    name: 'Google Sheets',
    description: 'Live connection to your Google Sheets',
    category: 'integrations',
    categoryLabel: 'Integration',
    iconType: 'gsheets',
    connected: false,
  },
  {
    id: 'onedrive',
    name: 'Microsoft OneDrive',
    description: 'Analyze your Personal OneDrive files and folders',
    category: 'integrations',
    categoryLabel: 'Integration',
    isNew: true,
    iconType: 'onedrive',
    connected: false,
  },
  {
    id: 'sharepoint',
    name: 'SharePoint',
    description: 'Analyze your SharePoint or OneDrive for Business files',
    category: 'integrations',
    categoryLabel: 'Integration',
    isNew: true,
    iconType: 'sharepoint',
    connected: false,
  },
  {
    id: 'gads',
    name: 'Google Ads',
    description: 'Analyze your data and manage your campaigns in Google Ads',
    category: 'integrations',
    categoryLabel: 'Integration',
    isNew: true,
    iconType: 'gads',
    connected: false,
  },
  {
    id: 'metaads',
    name: 'Meta Ads',
    description: 'Analyze your data and manage your campaigns in Meta Ads',
    category: 'integrations',
    categoryLabel: 'Integration',
    isNew: true,
    iconType: 'metaads',
    connected: false,
  },
];
